# Generated by Django 5.0.6 on 2024-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=500, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
